import { FamilyMember, PhaseConfig, EmergencyContact, ShiftRecord, CarePhase, ShiftType, PatientDailyReminder, PatientInfo } from './types';

export const PATIENT_INFO: PatientInfo = {
  name: 'Đinh Hồng Phong',
  diagnosis: 'Tai biến mạch máu não nặng (Đột quỵ diện rộng), liệt nửa người, thở máy/sonde',
  hospital: 'Bệnh viện Bạch Mai - Hà Nội',
  room: 'Khoa Hồi Sức Tích Cực (ICU) • Phòng 402, Giường 12',
  notes: 'Cần lật trở chống loét 2h/lần, kiểm tra SpO2 và hút đờm thường xuyên.',
  emergencyPhone: '0913 218 765',
};

export const FAMILY_MEMBERS: FamilyMember[] = [
  {
    id: 'mem-1',
    name: 'Bác Thành',
    relation: 'Bác cả (Trưởng ban điều phối)',
    phone: '0912 345 678',
    badgeColor: 'bg-blue-600',
    avatarInitials: 'BT',
    bgLight: 'bg-blue-50/90',
    borderLight: 'border-blue-300',
    textColor: 'text-blue-900',
    accentColor: 'bg-blue-600 text-white',
    pillBadge: 'bg-blue-100 text-blue-800 border-blue-300 font-bold',
  },
  {
    id: 'mem-2',
    name: 'Cô Lan',
    relation: 'Em gái bệnh nhân',
    phone: '0983 222 111',
    badgeColor: 'bg-emerald-600',
    avatarInitials: 'CL',
    bgLight: 'bg-emerald-50/90',
    borderLight: 'border-emerald-300',
    textColor: 'text-emerald-900',
    accentColor: 'bg-emerald-600 text-white',
    pillBadge: 'bg-emerald-100 text-emerald-800 border-emerald-300 font-bold',
  },
  {
    id: 'mem-3',
    name: 'Anh Dũng',
    relation: 'Con trai trưởng',
    phone: '0977 888 999',
    badgeColor: 'bg-indigo-600',
    avatarInitials: 'AD',
    bgLight: 'bg-indigo-50/90',
    borderLight: 'border-indigo-300',
    textColor: 'text-indigo-900',
    accentColor: 'bg-indigo-600 text-white',
    pillBadge: 'bg-indigo-100 text-indigo-800 border-indigo-300 font-bold',
  },
  {
    id: 'mem-4',
    name: 'Chị Mai',
    relation: 'Con dâu trưởng',
    phone: '0904 555 444',
    badgeColor: 'bg-rose-600',
    avatarInitials: 'CM',
    bgLight: 'bg-rose-50/90',
    borderLight: 'border-rose-300',
    textColor: 'text-rose-900',
    accentColor: 'bg-rose-600 text-white',
    pillBadge: 'bg-rose-100 text-rose-800 border-rose-300 font-bold',
  },
  {
    id: 'mem-5',
    name: 'Anh Hùng',
    relation: 'Con trai thứ',
    phone: '0918 666 777',
    badgeColor: 'bg-amber-600',
    avatarInitials: 'AH',
    bgLight: 'bg-amber-50/90',
    borderLight: 'border-amber-300',
    textColor: 'text-amber-950',
    accentColor: 'bg-amber-600 text-white',
    pillBadge: 'bg-amber-100 text-amber-900 border-amber-300 font-bold',
  },
  {
    id: 'mem-6',
    name: 'Chị Trang',
    relation: 'Con gái út',
    phone: '0936 123 456',
    badgeColor: 'bg-purple-600',
    avatarInitials: 'CT',
    bgLight: 'bg-purple-50/90',
    borderLight: 'border-purple-300',
    textColor: 'text-purple-900',
    accentColor: 'bg-purple-600 text-white',
    pillBadge: 'bg-purple-100 text-purple-800 border-purple-300 font-bold',
  },
  {
    id: 'mem-7',
    name: 'Cháu Quân',
    relation: 'Cháu đích tôn',
    phone: '0988 999 112',
    badgeColor: 'bg-teal-600',
    avatarInitials: 'CQ',
    bgLight: 'bg-teal-50/90',
    borderLight: 'border-teal-300',
    textColor: 'text-teal-900',
    accentColor: 'bg-teal-600 text-white',
    pillBadge: 'bg-teal-100 text-teal-800 border-teal-300 font-bold',
  },
];

export const PHASE_CONFIGS: Record<'phase1' | 'phase2', PhaseConfig> = {
  phase1: {
    id: 'phase1',
    name: 'Giai đoạn 1: Nằm Viện / Cấp Cứu ICU',
    subtitle: '3 ca/ngày (8 tiếng/ca) • Cần tối thiểu 1 người túc trực liên tục',
    description: 'Bệnh nhân nằm phòng Hồi sức tích cực. Bệnh viện chỉ cho phép 1 người thân vào chăm sóc tại một thời điểm.',
    shifts: [
      {
        type: 'morning',
        name: 'Ca Sáng',
        timeRange: '06:00 - 14:00 (8 tiếng)',
        requiredPax: 1,
      },
      {
        type: 'afternoon',
        name: 'Ca Chiều',
        timeRange: '14:00 - 22:00 (8 tiếng)',
        requiredPax: 1,
      },
      {
        type: 'night',
        name: 'Ca Đêm',
        timeRange: '22:00 - 06:00 sáng hôm sau (8 tiếng)',
        requiredPax: 1,
      },
    ],
  },
  phase2: {
    id: 'phase2',
    name: 'Giai đoạn 2: Phục Hồi / Chăm Sóc Tại Nhà',
    subtitle: '2 ca/ngày (12 tiếng/ca) • Bắt buộc 2 người/ca để cùng nâng đỡ & lật trở',
    description: 'Bệnh nhân đã xuất viện về nhà. Do thể trạng nặng, bắt buộc cần 2 người phối hợp: 1 người nâng đỡ, 1 người vệ sinh/bơm sữa.',
    shifts: [
      {
        type: 'day_12h',
        name: 'Ca Ngày (12 tiếng)',
        timeRange: '06:00 - 18:00 (12 tiếng)',
        requiredPax: 2,
      },
      {
        type: 'night_12h',
        name: 'Ca Đêm (12 tiếng)',
        timeRange: '18:00 - 06:00 sáng hôm sau (12 tiếng)',
        requiredPax: 2,
      },
    ],
  },
};

export const DEFAULT_EMERGENCY_CONTACTS: EmergencyContact[] = [
  {
    id: 'emg-1',
    name: 'Tổng đài Cấp cứu 115 Hà Nội',
    category: 'ambulance',
    phone: '115',
    note: 'Yêu cầu xe cấp cứu có bình oxy và máy hỗ trợ thở khẩn cấp',
    address: '11 Phan Chu Trinh, Hoàn Kiếm, Hà Nội',
    isPrimary: true,
  },
  {
    id: 'emg-2',
    name: 'BS. CKII Nguyễn Văn Hùng',
    category: 'doctor',
    phone: '0913 218 765',
    note: 'Trưởng kíp Hồi sức tích cực (ICU) BV Bạch Mai - Bác sĩ điều trị chính',
    address: 'Khoa Hồi sức tích cực, Tầng 4, Nhà A, BV Bạch Mai',
    isPrimary: true,
  },
  {
    id: 'emg-3',
    name: 'Bàn trực Khoa Hồi sức tích cực ICU',
    category: 'doctor',
    phone: '024 3869 3731',
    note: 'Số máy bàn trực 24/7 Khoa ICU Bạch Mai (Máy lẻ 402)',
    address: '78 Giải Phóng, Phương Mai, Đống Đa, Hà Nội',
    isPrimary: false,
  },
  {
    id: 'emg-4',
    name: 'Cô Loan - Điều dưỡng ngoài giờ & Phục hồi',
    category: 'nurse',
    phone: '0984 567 890',
    note: 'Hỗ trợ thay sonde dạ dày/tiểu, hút đờm sâu, tiêm truyền tại nhà',
    address: 'Gần viện Bạch Mai (Đến sau 15 phút khi gọi)',
    isPrimary: false,
  },
  {
    id: 'emg-5',
    name: 'Bác Nam (Nhà số 14 đối diện)',
    category: 'neighbor',
    phone: '0903 456 789',
    note: 'Hàng xóm thân thiết, hỗ trợ mở cổng xe cấp cứu và nâng người khẩn cấp',
    address: 'Số 14 ngõ 78 Giải Phóng',
    isPrimary: false,
  },
  {
    id: 'emg-6',
    name: 'Chị Mai Lan (Thủ quỹ gia đình)',
    category: 'family',
    phone: '0904 555 444',
    note: 'Giữ thẻ viện phí và quỹ thuốc cấp cứu của gia đình',
    address: 'Túc trực thường xuyên',
    isPrimary: false,
  },
];

export const SHIFTS_SHEET_HEADERS = [
  'id',
  'date',
  'shift_type',
  'shift_name',
  'phase',
  'required_pax',
  'assignees',
  'is_understaffed',
  'checklist_feeding',
  'checklist_meds',
  'checklist_hygiene',
  'checklist_turning',
  'handover_note',
  'handover_author',
  'handover_vitals_bp',
  'handover_vitals_spo2',
  'handover_vitals_pulse',
  'handover_vitals_temp',
  'updated_at',
];

export function buildDefaultShiftRecord(
  date: string,
  shiftCfg: { type: ShiftType; name: string; timeRange: string; requiredPax: number },
  phase: CarePhase
): ShiftRecord {
  return {
    id: `${date}_${shiftCfg.type}_${phase}`,
    date,
    type: shiftCfg.type,
    name: shiftCfg.name,
    timeRange: shiftCfg.timeRange,
    phase,
    requiredPax: shiftCfg.requiredPax,
    assignees: [],
    supporters: [],
    isUnderstaffed: true,
    checklist: {
      feeding: false,
      meds: false,
      hygiene: false,
      turning: false,
    },
    handover: {
      note: '',
      author: '',
      updatedAt: '',
      vitals: {
        bp: '',
        spo2: '',
        pulse: '',
        temp: '',
      },
    },
  };
}

export const DEFAULT_PATIENT_REMINDERS: PatientDailyReminder[] = [
  {
    id: 'reminder-meds-1',
    category: 'meds',
    title: 'Lưu ý thuốc huyết áp 14:00',
    content: 'Đo huyết áp trước khi cho uống Amlodipine 5mg lúc 14h. Nếu huyết áp tâm thu < 110 hoặc tâm trương < 70, hoãn uống và gọi BS Thắng.',
    author: 'Cô Lan (Em gái)',
    time: '08:15',
    isUrgent: true,
  },
  {
    id: 'reminder-feeding-2',
    category: 'feeding',
    title: 'Quy trình bơm súp qua sonde',
    content: 'Bơm súp ấm (khoảng 37°C) chậm qua sonde, mỗi cữ 250ml. Nâng đầu giường 45 độ trong và sau ăn ít nhất 30 phút để chống trào ngược sặc phổi.',
    author: 'Anh Dũng (Con trai)',
    time: '09:00',
    isUrgent: false,
  },
  {
    id: 'reminder-condition-3',
    category: 'condition',
    title: 'Hút đờm & theo dõi SpO2',
    content: 'Hôm nay đờm hơi đặc đục, nhớ vỗ rung lồng ngực trước khi hút đờm. Bật oxy 2L/phút nếu SpO2 tụt dưới 94%.',
    author: 'BS. Nguyễn Văn Thắng',
    time: '07:30',
    isUrgent: true,
  },
];

